plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // Spring Boot Starters
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web' // Changed from webmvc
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'

    // Database Driver
//    implementation 'org.postgresql:postgresql'
//    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'


    // Lombok (코드 자동 생성)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 개발 도구 (자동 재시작 등)
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // 테스트 관련 의존성
    testImplementation 'org.springframework.boot:spring-boot-starter-test' // 여러 test 스타터 통합
    
    // H2
//    runtimeOnly 'com.h2database:h2'
    
    
    // 시큐리티(비밀번호 해시)
    implementation 'org.springframework.boot:spring-boot-starter-security'
    
    
    // 웹소켓
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

}

tasks.named('test') {
	useJUnitPlatform()
}
